version: '3.8'

networks:
  nestjs-tilt-poc:
    name: 'nestjs-tilt-poc'

services:
  app_dev:
    container_name: app_dev
    working_dir: /app
    command: sh -c "npm run start:debug"
    build:
      context: .
      args:
        BUILD_STAGE: development
    ports:
      - '${PORT:-3000}:3000'
      - '${DEBUG_PORT:-9229}:9229'
    volumes:
      - .:/app
    networks:
      - nestjs-tilt-poc

  app_prod:
    container_name: app_prod
    build:
      context: .
    ports:
      - '${PORT:-3000}:3000'
    networks:
      - nestjs-tilt-poc
