apiVersion: v1
kind: Namespace
metadata:
  name: nestjs-tilt-poc
  labels:
    name: nestjs-tilt-poc

---

apiVersion: v1
kind: Service
metadata:
  name: nestjs-tilt-poc
  namespace: nestjs-tilt-poc

spec:
  selector:
    app: nestjs-tilt-poc
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-tilt-poc
  namespace: nestjs-tilt-poc
  labels:
    app: nestjs-tilt-poc

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nestjs-tilt-poc
  template:
    metadata:
      labels:
        app: nestjs-tilt-poc
    spec:
      containers:
        - name: nestjs-tilt-poc
          image: nestjs-tilt-poc
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          imagePullPolicy: IfNotPresent
      serviceAccountName: default
